### ISSUE TITLE
Build of many examples fails on the Arduino Due due to ambiguous method signatures

### ISSUE THREAD

**Issue by MartyMacGyver** [marekburiak/ILI9341_due#10]
Using Arduino IDE 1.8.2 + SAM board package 1.6.11 (both current) on Windows 7 I get the following error on many of the demos when targeting the Arduino Due. It appears the shader-aware versions of `fillRect()` and `fillRect_noTrans()` are recent additions and may not have been fully tested here.

	uTouchQuickPaint\uTouchQuickPaint.ino: In function 'void loop()':

	uTouchQuickPaint:103: error: call of overloaded 'fillRect(int, int, int, int16_t, int)' is ambiguous
	       tft.fillRect(33, 0, tft.width() - 65, tft.height(), ILI9341_BLACK);
	                                                                        ^
	uTouchQuickPaint\uTouchQuickPaint.ino:103:72: note: candidates are:

	In file included from uTouchQuickPaint\uTouchQuickPaint.ino:3:0:

	libraries\ILI9341_due/ILI9341_due.h:504:7: note: void ILI9341_due::fillRect(int16_t, int16_t, uint16_t, uint16_t, uint16_t)
	  void fillRect(int16_t x, int16_t y, uint16_t w, uint16_t h, uint16_t color);
	       ^
	libraries\ILI9341_due/ILI9341_due.h:505:7: note: void ILI9341_due::fillRect(int16_t, int16_t, uint16_t, uint16_t, uint16_t (*)(uint16_t, uint16_t))
	  void fillRect(int16_t x, int16_t y, uint16_t w, uint16_t h, uint16_t(*fillShader)(uint16_t rx, uint16_t ry));
	       ^

**Comment by marekburiak** [comment]
yea :) I was checking in a fix and I checked in my experimental stuff with it without testing the examples. I'll look into it, thanks for letting me know.
