### ISSUE TITLE
Teensy support

### ISSUE THREAD

**Issue by Jonage** [marekburiak/ILI9341_due#23]
This is utterly awesome library. I'm really missing it on Teensy. Is there any alternative?
Using basic Adafruit basic library is like living in a stone age.

**Comment by jonnystokes** [comment]
This is an awesome library.
Can this library be made compatible with teensy 4.0?

**Comment by marekburiak** [comment]
Oh yea, it can be made compatible, the question is...who's gonna do it :)

**Comment by Jonage** [comment]
I tried... But - it is toooooo much :-D

**Comment by marekburiak** [comment]
I agree...somebody needs to spend considerable knowledge, time, patience and enthusiasm to get this converted to teensy. And I have none of these at this time :)

**Comment by ImpulseAdventure** [comment]
You are right... Marek’s library is definitely a fantastic library!

In the interim, if you need an optimization for Teensy, you may want to also take a look at ili9341_t3. Porting can be a lot of work (as evidenced by the PJRC threads), especially if aiming to retain the level of performance that Marek has already achieved for us with the Due and other AVRs. Have fun :)
