### ISSUE TITLE
Backgroundcolor Font

### ISSUE THREAD

**Issue by Mcubus** [marekburiak/ILI9341_due#7]
Is it possible not to have a background color for text? 
In the ILI9341_due.cpp is the declariation of the variable "_fontBgColor = ILI9341_BLACK;" set as standard. I thought I could comment out that one to erase the backgroundcolor. But unfortunately not. Is there a way to change that? Or is it possible to read the color behind the text and set that one to the fonts background color?

**Comment by marekburiak** [comment]
Hi, use the [setFontMode](http://marekburiak.github.io/ILI9341_due/#setFontMode56) function

**Comment by Mcubus** [comment]
Oh my god - I was so blind! Thank you a lot. Your code is amazing and very helpfull!
